default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release"
    firebase_app_distribution(
    app: "1:1056481040552:android:35c1de8a4e147873a14a9d",
    firebase_cli_token: ENV['FIREBASE_CLI_TOKEN'],
    android_artifact_type: "APK",
    android_artifact_path: "D:/flutter/flutter_project/app_firebase_distribution/build/app/outputs/flutter-apk/app-release.apk",
    testers: "elesawy928@gmail.com",
    release_notes: "new release with firebase distribution"
    
  )
  end
end
